### ISSUE TITLE
V4 hype

### ISSUE THREAD

**Issue by Jesseman1** [keilladraconis/Fallout-Vore#21]
I'm super excited for V4 to release and see the new features! I'm assuming I will need to start a new game for it though.

Will this also fix some of the vore perks that didn't work right before? (For example, Fast Metabolism only healing after digestion and not during, or being able to eat robots and gouls without getting the perks first, or being able to eat higher than capacity if you are not completely full and the prey is dead.)

Also, I once saw someone use this mod on YouTube, and the bellies had physics too, how would I get that to work, or is that not a feature anymore?

**Comment by keilladraconis** [comment]
Belly does have physics, you have to install OCBP and F4SE. I also tweaked the API to balance physics with how large your character is because otherwise your belly wobbles while it's flat and empty.

I'm not going to preserve any perks in their current forms. There are a lot of ideas there but I really want to reduce complexity and improve the gameplay synergy with the base game through optional simulation modes.

There are also a large number of players that don't care about the gameplay at all and simply use it as a role-playing tool, so for them the systemic clarification and wider set of toggleable modes/options and overrides will be an improvement I hope.

I myself am interested in the gamer/simulation/predator side of things so that's where I'm focusing effort right now.

**Comment by Jesseman1** [comment]
I have the OCBPC mod and F4SE installed, but I never got any belly physics. The flat, non-vore belly jiggles with physics properly, but the big belly never moves at all. Does it have to be OCBP specifically? Would using the fox race mod(and vore patch for it) affect this?
